In [ ]:
#Problem 1(1)
import numpy as np
first = np.empty((2,2))
print(first)

array([[0., 0.],
       [0., 0.]])

In [ ]:
#Problem 1(2)
array = np.ones((4,2))
print(array)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#Problem 1(3)
value = 8
full = np.full((2,2), value)
full

array([[8, 8],
       [8, 8]])

In [ ]:
#Problem 1(4)
array = ([[1,2,3], [2,3,4]])
zeros = np.zeros_like(array)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#Problem 1(5)
array = ([[2,4,5], [1,3,5]])
ones = np.ones_like(array)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#Problem 1(6)
new_list = [1,2,3,4]
np_array = np.array(new_list)
print('Converted numpy array is', np_array)

Converted numpy array is [1 2 3 4]


In [ ]:
#Problem 2(1)
array = np.arange(10,50).reshape(10,4)
array


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49]])

In [ ]:
#Problem 2(2)
array = np.arange(0,9).reshape(3,3)

array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#Problem 2(3)
array = np.eye(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Problem 2(4)
array = np.random.random(size =(30)).reshape(10,3)
print(array)

array.mean()

[[0.42396631 0.49156586 0.74664904]
 [0.62128348 0.88007502 0.93581293]
 [0.2377994  0.37147215 0.2663677 ]
 [0.76991574 0.88708265 0.23768184]
 [0.61315269 0.34167096 0.75701785]
 [0.59321261 0.39976783 0.57096205]
 [0.68943597 0.95097742 0.37224914]
 [0.57310521 0.63400707 0.1149122 ]
 [0.09257053 0.60376065 0.75887832]
 [0.6981168  0.94381432 0.82026333]]


0.579918235434761

In [ ]:
#Problem 2(5)
array = np.random.randint(1,101, size=100)
array2 = array.reshape(10,10)
print(array2)
print("Minimum value in the array is: ",array2.min())
print("Maximum value in the array is: ",array2.max())


[[77 32 91 59 96 72 75 26 92 51]
 [73 61 50 43 65 14 40  3 82 80]
 [32  1 66 76 81 87 67 70 36 28]
 [72 16 58 91 94 90 50 35 81 23]
 [55 38 94 11 13 88 38 25 87 12]
 [89 15 59 75 51 91 38 42 78 31]
 [93 26 11 75 42 23 69 46 20 95]
 [72 61 44 67 96 89 38 38 20  2]
 [85 75 35 65 89 22 51 94 50 86]
 [57 95 23 59 79 93 86 62 33 41]]
Minimum value in the array is:  1
Maximum value in the array is:  96


In [ ]:
#Problem 2(6)
array = np.zeros(10)
print("Before:",array)
array[4] = 1
print("After:",array)

Before: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Problem 2(7)
arr = [1,2,0,0,4,0]
reversed_arr = arr[::-1]
print('Reversed array is:',reversed_arr)

Reversed array is: [0, 4, 0, 0, 2, 1]


In [36]:
#Problem 2(8)
import numpy as np

rows = 5
cols = 4
arr = np.zeros((rows, cols))

arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [5]:
#Problem 2(9)
import numpy as np
arr = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            arr[i, j] = 0
        else:
            arr[i, j] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [28]:
#Problem 3(1)
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12]);

print("Addition of x and y is:\n", np.add(x,y))

print("Addition of v and w is:\n", np.add(v,w))

Addition of x and y is:
 [[ 6  8]
 [10 13]]
Addition of v and w is:
 [20 22]


In [30]:
#Problem 3(2)
print("Subtraction of x and y:\n", np.subtract(x,y))

print("Subtraction of v and w:\n", np.subtract(v,w))

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Subtraction of v and w:
 [-2 -2]


In [34]:
#Problem 3(3)
print("Product of x with 8 is:\n", np.multiply(x,8))
print("Product of y with 2 is:\n", np.multiply(y,2))
print("Product of v with 4 is:", np.multiply(v,4))
print("Produc of w with 3 is:", np.multiply(w,3))

Product of x with 8 is:
 [[ 8 16]
 [24 40]]
Product of y with 2 is:
 [[10 12]
 [14 16]]
Product of v with 4 is: [36 40]
Produc of w with 3 is: [33 36]


In [35]:
#Problem 3(4)
print("Square of elements in x is:\n", np.square(x))
print("Square of elements in y is:\n", np.square(y))
print("Square of elements in v is:\n", np.square(v))
print("Square of elements in w is:\n", np.square(w))

Square of elements in x is:
 [[ 1  4]
 [ 9 25]]
Square of elements in y is:
 [[25 36]
 [49 64]]
Square of elements in v is:
 [ 81 100]
Square of elements in w is:
 [121 144]


In [21]:
#Problem 3(5)
dot_v_w = np.dot(v, w)
print("Dot product of v and w:", dot_v_w)

dot_x_v = np.dot(x, v)
print("Dot product of x and v:\n", dot_x_v)

dot_x_y = np.dot(x, y)
print("Dot product of x and y:\n", dot_x_y)


Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [23]:
#Problem 3(6)
concat1 = np.concatenate((x, y), axis=0)
print("Concatenation of x and y along rows:\n", concat1)

concat2 = np.vstack((v, w)).T
print("Concatenation of v and w along columns:\n", concat2)

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]


In [26]:
#Problem 3(7)
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_x_v)
except ValueError as e:
    print("Error:", e)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [37]:
#Problem 4(1)
import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)

result = np.dot(A, A_inv)

print("A * A^-1", result)

I = np.eye(2)
print("Identity matrix I:\n", I)


A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix I:
 [[1. 0.]
 [0. 1.]]


In [39]:
#Problem 4(2)
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

are_equal = np.array_equal(AB, BA)
print("Is AB equal to BA?", are_equal)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False


In [42]:
#Problem 4(3)
ab_transpose = np.transpose(AB)
bt_at_transpose = np.dot(np.transpose(B), np.transpose(A))

print("(AB)^T:\n", ab_transpose)
print("B^T * A^T:\n", bt_at_transpose)

is_transpose_property_holding = np.array_equal(ab_transpose, bt_at_transpose)
print("Does (AB)^T equal B^T * A^T?", is_transpose_property_holding)


(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Does (AB)^T equal B^T * A^T? True


In [44]:
#Problem 4(4)

import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([[-1],
              [-3],
              [9]])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("The values of [x, y, z] is:\n", X)

The values of [x, y, z] is:
 [[ 2.]
 [ 1.]
 [-2.]]
